set_property IOSTANDARD LVCMOS33 [get_ports ENET0_GMII_RX_CLK_0]
set_property IOSTANDARD LVCMOS33 [get_ports ENET0_GMII_TX_CLK_0]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_ETHERNET_0_0_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_ETHERNET_0_0_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_TX_EN_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_RXD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_RXD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_RXD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_RXD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_TXD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_TXD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_TXD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_TXD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ENET0_GMII_RX_DV_0]
set_property PACKAGE_PIN J18 [get_ports ENET0_GMII_RX_CLK_0]
set_property PACKAGE_PIN H18 [get_ports ENET0_GMII_TX_CLK_0]
set_property PACKAGE_PIN D20 [get_ports {ENET0_GMII_TX_EN_0[0]}]
set_property PACKAGE_PIN M18 [get_ports ENET0_GMII_RX_DV_0]
set_property PACKAGE_PIN M20 [get_ports MDIO_ETHERNET_0_0_mdc]
set_property PACKAGE_PIN M19 [get_ports MDIO_ETHERNET_0_0_mdio_io]
set_property PACKAGE_PIN L20 [get_ports {ENET0_RXD[0]}]
set_property PACKAGE_PIN L19 [get_ports {ENET0_RXD[1]}]
set_property PACKAGE_PIN H20 [get_ports {ENET0_RXD[2]}]
set_property PACKAGE_PIN J20 [get_ports {ENET0_RXD[3]}]
set_property PACKAGE_PIN G20 [get_ports {ENET0_TXD[0]}]
set_property PACKAGE_PIN G19 [get_ports {ENET0_TXD[1]}]
set_property PACKAGE_PIN F20 [get_ports {ENET0_TXD[2]}]
set_property PACKAGE_PIN F19 [get_ports {ENET0_TXD[3]}]

#   LED PIN    #
set_property PACKAGE_PIN D19 [get_ports led_o]
set_property IOSTANDARD LVCMOS33 [get_ports led_o]

#   ADC PINS   #
set_property IOSTANDARD LVCMOS33 [get_ports adc_clk_o_0]
set_property PACKAGE_PIN Y17 [get_ports adc_clk_o_0]

set_property IOSTANDARD LVCMOS33 [get_ports adc_data_i_0[*]]
set_property PACKAGE_PIN Y16 [get_ports {adc_data_i_0[0]}]
set_property PACKAGE_PIN Y14 [get_ports {adc_data_i_0[1]}]
set_property PACKAGE_PIN W14 [get_ports {adc_data_i_0[2]}]
set_property PACKAGE_PIN T15 [get_ports {adc_data_i_0[3]}]
set_property PACKAGE_PIN T14 [get_ports {adc_data_i_0[4]}]
set_property PACKAGE_PIN U14 [get_ports {adc_data_i_0[5]}]
set_property PACKAGE_PIN R14 [get_ports {adc_data_i_0[6]}]
set_property PACKAGE_PIN W13 [get_ports {adc_data_i_0[7]}]
set_property PACKAGE_PIN V12 [get_ports {adc_data_i_0[8]}]
set_property PACKAGE_PIN U12 [get_ports {adc_data_i_0[9]}]
set_property PACKAGE_PIN T12 [get_ports {adc_data_i_0[10]}]
set_property PACKAGE_PIN T11 [get_ports {adc_data_i_0[11]}]

#   DAC PINS   #
set_property IOSTANDARD LVCMOS33 [get_ports dac_clk_o_0]
set_property PACKAGE_PIN D18 [get_ports dac_clk_o_0]

set_property IOSTANDARD LVCMOS33 [get_ports dac_data_o_0[*]]
set_property PACKAGE_PIN L17 [get_ports {dac_data_o_0[0]}]
set_property PACKAGE_PIN L16 [get_ports {dac_data_o_0[1]}]
set_property PACKAGE_PIN L15 [get_ports {dac_data_o_0[2]}]
set_property PACKAGE_PIN L14 [get_ports {dac_data_o_0[3]}]
set_property PACKAGE_PIN K18 [get_ports {dac_data_o_0[4]}]
set_property PACKAGE_PIN K17 [get_ports {dac_data_o_0[5]}]
set_property PACKAGE_PIN J14 [get_ports {dac_data_o_0[6]}]
set_property PACKAGE_PIN K14 [get_ports {dac_data_o_0[7]}]
set_property PACKAGE_PIN G18 [get_ports {dac_data_o_0[8]}]
set_property PACKAGE_PIN G17 [get_ports {dac_data_o_0[9]}]
set_property PACKAGE_PIN F17 [get_ports {dac_data_o_0[10]}]
set_property PACKAGE_PIN F16 [get_ports {dac_data_o_0[11]}]
set_property PACKAGE_PIN E18 [get_ports {dac_data_o_0[12]}]
set_property PACKAGE_PIN E19 [get_ports {dac_data_o_0[13]}]

#   CLK PIN    #L16
set_property PACKAGE_PIN U18 [get_ports clk_in_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in_0]
create_clock -name clk_in_0 -period 100.000 [get_ports clk_in_0]

#   QRZ  PIN   #
set_property PACKAGE_PIN H16 [get_ports q_clk_i_0]
set_property IOSTANDARD LVCMOS33 [get_ports q_clk_i_0]
create_clock -name q_clk_i_0 -period 20.000 [get_ports q_clk_i_0]

#   TRIGGER PIN #
set_property PACKAGE_PIN T17 [get_ports trig_i_0]
set_property IOSTANDARD LVCMOS33 [get_ports trig_i_0]